name: artnet_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  lottie: ^3.1.2
  gradient_borders: ^1.0.1
  flutter_screenutil: ^5.9.3
  udp: ^5.0.3
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    # - assets/images/
    # - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 100
