name: artnet_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  lottie: ^3.1.2
  gradient_borders: ^1.0.1
  flutter_screenutil: ^5.9.3
  udp: ^5.0.3
  circular_countdown_timer: ^0.2.4
  wifi_info_flutter: ^2.0.2
  connectivity_plus: ^6.1.0
  wifi_ip_details: ^1.0.0
  flutter_colorpicker: ^1.1.0
  interactive_slider: ^0.4.0
  keyboard_avoider: ^0.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flex_color_picker: ^3.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    # - assets/images/
    # - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 100
          
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Italic.ttf
          style: italic